# Generated by Django 5.0.1 on 2024-01-18 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_order_orderproduct_order_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sum',
        ),
    ]
