# Generated by Django 5.0.1 on 2024-01-18 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_remove_product_sum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ'},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={'verbose_name': 'Товар из корзины'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductNormal', to='webapp.category', verbose_name='Категория'),
        ),
    ]
